// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtsEoJsaoskgBjAMSl4FLqr9kq_K__jfA',
    appId: '1:752963174826:web:ee9f4360be1a3b7c562bd3',
    messagingSenderId: '752963174826',
    projectId: 'circketnoti',
    authDomain: 'circketnoti.firebaseapp.com',
    storageBucket: 'circketnoti.firebasestorage.app',
    measurementId: 'G-ZVLBC6R412',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN6k0q1zNuarcOoBnPyJmznIW5oxRZbHk',
    appId: '1:752963174826:android:5cdd66c43b4dca35562bd3',
    messagingSenderId: '752963174826',
    projectId: 'circketnoti',
    storageBucket: 'circketnoti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA26ayGwRkRhb6CpowLLc-EyBJLHm3V_zo',
    appId: '1:752963174826:ios:83316f16f156504c562bd3',
    messagingSenderId: '752963174826',
    projectId: 'circketnoti',
    storageBucket: 'circketnoti.firebasestorage.app',
    iosBundleId: 'com.example.cricketAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA26ayGwRkRhb6CpowLLc-EyBJLHm3V_zo',
    appId: '1:752963174826:ios:83316f16f156504c562bd3',
    messagingSenderId: '752963174826',
    projectId: 'circketnoti',
    storageBucket: 'circketnoti.firebasestorage.app',
    iosBundleId: 'com.example.cricketAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtsEoJsaoskgBjAMSl4FLqr9kq_K__jfA',
    appId: '1:752963174826:web:173b62e4b36d40cb562bd3',
    messagingSenderId: '752963174826',
    projectId: 'circketnoti',
    authDomain: 'circketnoti.firebaseapp.com',
    storageBucket: 'circketnoti.firebasestorage.app',
    measurementId: 'G-3P1MKK3SQ4',
  );
}